name: CD_RELEASE

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      
      - name: Run the tests
        run: mvn -B -f pom.xml test jacoco:prepare-agent jacoco:report
          
      - name: SonarCloud Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -V verify sonar:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=pepaulo8 \
          -Dsonar.projectKey=pepaulo8_DevOpsHackathon \
          -Dsonar.language=java \
          -Dsonar.java.coveragePlugin=jacoco \
          -Dmaven.test.skip=true

      - name: Install SSH key
        run: echo "$RELEASE_PRIVATE_KEY" > key && chmod 600 key

      - name: Deploy application
        run: |
          scp -i key target/java-api.jar ${{ secrets.USER_NAME }}@${{ secrets.RELEASE_HOST }}:/java-api/java-api.jar
          ssh -i key ${{ secrets.USER_NAME }}@${{ secrets.RELEASE_HOST }} "/usr/bin/java -jar -Dserver.port=8080 /java-api/java-api.jar"

